version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
  # localstack:
  #   image: localstack/localstack:latest
  #   ports:
  #     - "4566:4566"
  #     - "4510-4559:4510-4559"
  #   environment:
  #     - SERVICES=lambda,s3
  #     - AWS_BUCKET_ACCESS_KEY_ID=test
  #     - AWS_BUCKET_SECRET_ACCESS_KEY=test
  #     - AWS_DEFAULT_REGION=us-east-1
  #     - PERSISTENCE=1
  #     - POST_INIT_SCRIPT=/etc/localstack/init/ready.d/init-all.sh
  #   volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock"
  #    - ./.docker/localstack/cors-config.json:/etc/localstack/init/ready.d/utils/cors-config.json
  #    - ./.docker/localstack/init-s3.sh:/etc/localstack/init/ready.d/utils/init-s3.sh
  #    - ./.docker/localstack/init-cors.sh:/etc/localstack/init/ready.d/utils/init-cors.sh
  #    - ./.docker/localstack/init-all.sh:/etc/localstack/init/ready.d/init-all.sh
